#!/bin/bash

# https://www.shellhacks.com/bash-colors/
NORMAL='\[\033[00m\]'
BLACK='\[\033[0;30m\]'
RED='\[\033[0;31m\]'
GREEN='\[\033[0;32m\]'
BROWN='\[\033[0;33m\]'
BLUE='\[\033[0;34m\]'
PURPLE='\[\033[0;35m\]'
CYAN='\[\033[0;36m\]'
LIGHTGRAY='\[\033[0;37m\]'

RED_BOLD='\[\033[1;31m\]'
GREEN_BOLD='\[\033[1;32m\]'
BROWN_BOLD='\[\033[1;33m\]'
BLUE_BOLD='\[\033[1;34m\]'
PURPLE_BOLD='\[\033[1;35m\]'
CYAN_BOLD='\[\033[1;36m\]'
LIGHTGRAY_BOLD='\[\033[1;37m\]'
PS1="${BLUE}(${RED}\w${BLUE}) ${NORMAL}\h ${RED}\$ ${NORMAL}"
#PS1="${debian_chroot:+($debian_chroot)}${BGREEN}\u@\h${NORMAL}:${BBLUE}\w${NORMAL}\$ "
#PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '

# If this is an xterm set the title to user@host:dir
#case "$TERM" in
#xterm*|rxvt*)
#    PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME}: ${PWD/$HOME/~}\007"'
#    ;;
#*)
#    ;;
#esac
