#!/bin/sh

pathmunge() {
	if ! echo "$PATH" | /bin/grep -q "\(^\|:\)$1\($\|:\)"; then
		if [ "$2" = "after" ]; then
			PATH="$PATH:$1"
		else
			PATH="$1:$PATH"
		fi
	fi
}

# Put environment variables here

#export WIN_IP=$(grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}' /etc/resolv.conf)
export WIN_IP="$(awk '/nameserver/ { print $2 }' < /etc/resolv.conf)"
export WSL_IP=$(ip addr show eth0 | grep 'inet ' | cut -f 6 -d ' ' | cut -f 1 -d '/')

# Windows directory including Linux scripts
export GOOGLE_SCRIPT_DIR="/mnt/c/Users/Brian/Google Drive/Scripts/Linux"

export WIN_ANDROID_HOME="/mnt/c/Android/sdk"
export WIN_ANDROID_NDK="$WIN_ANDROID_HOME/ndk-bundle"

### BEGIN setupAndroidSDK.sh ###
export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"

pathmunge "$JAVA_HOME/bin"

export ANDROID_HOME="$HOME/Android"
pathmunge "$ANDROID_HOME/tools"
pathmunge "$ANDROID_HOME/tools/bin"
pathmunge "$ANDROID_HOME/platform-tools"
### END setupAndroidSDK.sh ###

export ANDROID_NDK="$ANDROID_HOME/ndk-bundle"
export NDK="$ANDROID_NDK"
pathmunge "$NDK"

export NDK_PREBUILT="$NDK/toolchains/llvm/prebuilt/linux-x86_64/bin"
pathmunge "$NDK_PREBUILT"

export BUILD_TOOLS_VER="30.0.0"
export BUILD_TOOLS="$ANDROID_HOME/build-tools/$BUILD_TOOLS_VER"
pathmunge "$BUILD_TOOLS"

export ANDROID_ADB_SERVER_PORT=${ANDROID_ADB_SERVER_PORT:-5037}
export ANDROID_ADB_SERVER_HOST=$WIN_IP
export ADB_SERVER_SOCKET=tcp:$ANDROID_ADB_SERVER_HOST:$ANDROID_ADB_SERVER_PORT

# Configure general X11 connection
export DISPLAY="$WIN_IP":0
#export DISPLAY="$WIN_IP:0"

# Enable Direct Rendering
export LIBGL_ALWAYS_INDIRECT=1

pathmunge "$HOME/.dotnet:$HOME/dotnet"

export PATH
#AdbDev1="${ANDROID_SERIAL:-$(adb devices | sed '2s/[[:space:]].*//p;d')}"
